# Generated by Django 3.2.4 on 2021-06-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_nursery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nursery',
            options={'verbose_name_plural': 'Nurseries'},
        ),
    ]
