# Generated by Django 3.2.4 on 2021-06-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20210629_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='price',
        ),
    ]
