# Generated by Django 3.2.4 on 2021-06-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_nursery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursery',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
