# Generated by Django 3.2.4 on 2021-06-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_nursery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='price',
        ),
        migrations.AddField(
            model_name='nursery',
            name='retail',
            field=models.IntegerField(default=0, verbose_name='Retail'),
        ),
    ]
