# Generated by Django 3.2.4 on 2021-06-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20210629_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='retail',
        ),
    ]
