# Generated by Django 3.2.4 on 2021-06-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_remove_nursery_retail'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='Price'),
        ),
    ]
