# Generated by Django 3.2.4 on 2021-06-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_nursery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='price',
        ),
    ]
