# Generated by Django 3.2.4 on 2021-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_remove_nursery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='retail',
            field=models.IntegerField(default=0, verbose_name='Retail'),
        ),
    ]
