# Generated by Django 3.2.4 on 2021-06-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_remove_nursery_retail'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='price',
            field=models.CharField(default=True, max_length=255, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
