# Generated by Django 3.2.4 on 2021-07-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_auto_20210629_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nursery2',
        ),
    ]
