# Generated by Django 3.2.4 on 2021-07-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_delete_nursery2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nursery',
        ),
    ]
