# Generated by Django 3.2.4 on 2021-07-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_nursery'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='price',
            field=models.CharField(default=0, max_length=150, verbose_name='Price'),
        ),
    ]
