# Generated by Django 3.2.4 on 2021-07-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_nursery_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='retail',
        ),
        migrations.AlterField(
            model_name='nursery',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
