# Generated by Django 3.2.4 on 2021-07-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_auto_20210630_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='price',
        ),
        migrations.AddField(
            model_name='nursery',
            name='retail',
            field=models.IntegerField(default=0, verbose_name='Retail'),
        ),
    ]
